Investigador.create(email: 'aguiluz@unam.mx', password:'123456', programa_id: '3', nombres: 'Maya Victoria', apPat: 'Aguiluz', apMat: 'Ibargüen', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Ciencias Sociales, Facultad Latinoamericana de Ciencias Sociales
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM ', correo: 'mayaguiluz@hotmail.com', telefono: '5623-0202', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AUIM611025', foto:'1MVAguiluz.jpg')
Investigador.create(email: 'mareugalv@gmail.com', password: '123456', programa_id: '10', nombres: 'María Eugenia', apPat: 'Alvarado', apMat: 'Rodríguez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Derecho y Sociedad', historiaAcademica: 'Doctora en Pedagogía, Facultad de Filosofía y Letras, UNAM
Maestra en Pedagogía, Facultad de Filosofía y Letras, UNAM
Licenciada en Pedagogía, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0438', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AARE571121', foto: '2MEAlvarado.jpg')
Investigador.create(email: 'lalvarez@unam.mx', password: '123456', programa_id: '6', nombres: 'Lucía', apPat: 'Álvarez', apMat: 'Enríquez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II
Miembro de la Red Mexicana de Investigadores sobre Sociedad Civil (Remisoc)', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0424', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AAEL571110', foto: '3LAlvarez.jpg')
Investigador.create(email: 'j.antonio.amoz@gmail.com', password: '123456', programa_id: '4', nombres: 'José Antonio', apPat: 'Amozurrutia', apMat: 'de María y Campos', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Cibercultura y Desarrollo de Comunidades de Conocimiento', historiaAcademica: 'Doctor en Sociología, Universidad de Zaragoza, España
Maestro en Sociología, Universidad de Zaragoza, España
Ingeniero Químico, Universidad Iberoamericana', correo: '', telefono: '5623-0222', extension:'42763', humanindex: '', foto: '4JAAmozurrutia.jpg')
Investigador.create(email: 'blazquez@unam.mx', password: '123456', programa_id: '2', nombres: 'Norma', apPat: 'Blazquez', apMat: 'Graf', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctora en Filosofía, Facultad de Filosofía y Letras, UNAM
Maestra en Ciencias, Especialidad en Fisiología y Biofísica, Centro de Investigación y Estudios Avanzados, IPN
Licenciada en Psicología, Universidad Anáhuac', correo: '', telefono: '5623-0222', extension:'42767', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=BAGN560906', foto: '5NBlazquez.jpg')
Investigador.create(email: 'unam.cabrera@gmail.com', password: '123456', programa_id: '3', nombres: 'Gloria Patricia', apPat: 'Cabrera', apMat: 'López', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Literatura, Facultad de Filosofías y Letras, UNAM
Estudios de Sociología de la literatura en la École de Hautes Études en Sciences Sociales, de París, y de Semiótica en la Università degli Studi, de Bolonia
Licenciada en Lengua y Literaturas Hispánicas, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0447', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=CALG520412', foto: '6GPCabrera.jpg')
Investigador.create(email: 'cadenaroa@gmail.com', password: '123456', programa_id: '8', nombres: 'Gerardo Jorge', apPat: 'Cadena', apMat: 'Roa', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel III
Miembro Regular de la Academia Mexicana de Ciencias
Miembro de la Junta de Gobierno de la UNAM', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctor en Sociología, Universidad de Wisconsin-Madison, USA
Maestro en Sociología, Universidad de Wisconsin-Madison, USA
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0442', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=CARG570709', foto: '7GJCadena.jpg')
Investigador.create(email: 'marthap@unam.mx', password: '123456', programa_id: '9', nombres: 'Martha Patricia', apPat: 'Castañeda', apMat: 'Salgado', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa Investigación Feminista', historiaAcademica: 'Doctora en Antropología, Instituto de Investigaciones Antropológicas, UNAM
Maestra en Antropología Social, Universidad Iberoamericana
Licenciada en Antropología, Universidad Autónoma de Puebla', correo: '', telefono: '5623-0222', extension:'42764', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=%20CASM631014', foto: '8MPCastaneda.jpg')
Investigador.create(email: 'elvira.concheiro@gmail.com', password: '123456', programa_id: '5', nombres: 'María Elvira', apPat: 'Concheiro', apMat: 'Bórquez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestría en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42779', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=COBE541016', foto: '9MEConcheiro.jpg')
Investigador.create(email: 'molotla.cf@unam.mx', password: '123456', programa_id: '7', nombres: 'Felipe', apPat: 'Contreras', apMat: 'Molotla', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Por Artículo 51', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel B', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación La Producción de Bienes y Servicios Básicos', historiaAcademica: 'Doctor en Estudios de Población, El Colegio de México
Maestro en Población, Facultad Latinoamericana de Ciencias Sociales, Sede Académica México
Licenciado en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0263', extension:'', humanindex: '', foto: '10FContreras.jpg')
Investigador.create(email: 'consuar@unam.mx', password: '123456', programa_id: '7', nombres: 'Enrique', apPat: 'Contreras', apMat: 'Suárez', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación La Producción de Bienes y Servicios Básicos', historiaAcademica: 'Doctor en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestro en Ciencias Sociales, Facultad Latinoamericana de Ciencias Sociales, Santiago de Chile
Licenciado en Ciencias Sociales, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0261', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=COSE410224', foto: '11EContreras.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '12OCorreas.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '13SLDaville.jpg')

Investigador.create(email: 'jose@delval1.com', password: '123456', programa_id: '', nombres: 'José Manuel', apPat: 'Del Val', apMat: 'Blanco', nombramiento: 'Investigador', categoria: 'Asociado', nivel: 'C', definitividad: 'Definitivo', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '14JMDelVal.jpg')
Investigador.create(email: 'giandelgado@unam.mx', password: '123456', programa_id: '6', nombres: 'Gian Carlo', apPat: 'Delgado', apMat: 'Ramos', nombramiento: 'Investigador', categoria: 'Definitivo', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctor en Ciencias Ambientales, Universidad Autónoma de Barcelona, España
Maestro en Economía Ecológica y Gestión Ambiental, Universidad Autónoma de Barcelona, España
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0222', extension:'42777', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=DERG780608', foto: '15GCDelgado.jpg')
Investigador.create(email: 'estradaalbateresa52@gmail.com', password: '123456', programa_id: '3', nombres: 'Alba Teresa', apPat: 'Estrada', apMat: 'Castañón', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Ciencia Social con Especialidad en Sociología, El Colegio de México
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0477', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=EACA511030', foto: '16ATEstrada.jpg')
Investigador.create(email: 'dfavelag@unam.mx', password: '123456', programa_id: '8', nombres: 'Diana Margarita', apPat: 'Favela', apMat: 'Gavia', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencia Política, Universidad de Tulane, USA
Maestra en Economía Política Internacional, Centro de Investigación y Docencia Económicas, A. C.
Maestra en Ciencia Política, Universidad de Tulane, USA
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0421', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=FAGD590416', foto: '17DMFavela.jpg')
Investigador.create(email: 'vfloresolea@gmail.com', password: '123456', programa_id: '5', nombres: 'Víctor', apPat: 'Flores', apMat: 'Olea', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: '', estimulos: '', sociedades: '', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Estudios de Doctorado en Ciencias Políticas, Escuela Práctica de Altos Estudios, París
Licenciado en Derecho, Facultad de Derecho, UNAM', correo: '', telefono: '5623-0264', extension:'', humanindex: '', foto: '18VFlores.jpg')
Investigador.create(email: 'olivgall@unam.mx', password: '123456', programa_id: '8', nombres: 'Olivia Joanna', apPat: 'Gall', apMat: 'Sonabend', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II
Miembro de la Academia Mexicana de Ciencias', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencia Política, Institut d’ Ètudes Politiques de Grenoble, Francia
Maestra en Ciencia Política, Institut d’ Ètudes Politiques de Grenoble, Francia
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42775', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GASO561021', foto: '19OGall.jpg')
Investigador.create(email: 'joseg@unam.mx', password: '123456', programa_id: '5', nombres: 'José Guadalupe', apPat: 'Gandarilla', apMat: 'Salgado', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Doctor en Filosofía Política, Universidad Autónoma Metropolitana-Iztapalapa
Maestro en Estudios Latinoamericanos, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0222', extension:'42766', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GASG671212', foto: '20JGGandarilla.jpg')
Investigador.create(email: 'tzolkin4@unam.mx', password: '123456', programa_id: '4', nombres: 'Jorge Alejandro', apPat: 'González', apMat: 'Sánchez', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel III', adscripcion: 'Programa de Investigación Cibercultura y Desarrollo de Comunidades de Conocimiento', historiaAcademica: 'Doctor en Ciencias Sociales, Universidad Iberoamericana
Maestro en Sociología, Universidad Iberoamericana
Licenciado en Comunicación, Universidad Iberoamericana', correo: 'jorge@labcomplex.net', telefono: '5623-0449', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GOSJ541129', foto: '21JAGonzalez.jpg')
Investigador.create(email: 'guillermo.guajardo@unam.mx', password: '123456', programa_id: '2', nombres: 'Guillermo Agustín', apPat: 'Guajardo', apMat: 'Soto', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Maestro en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Licenciado en Historia, Facultad de Filosofía y Humanidades, Universidad de Chile', correo: '', telefono: '5623-0431', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GUSG620619', foto: '22GAGuajardo.jpg')
Investigador.create(email: 'FabrizzioMc@gmail.com', password: '123456', programa_id: '1', nombres: 'Siobhan Fenella', apPat: 'Guerrero', apMat: 'Mc Manus', nombramiento: 'Investigadora', categoria: 'Asociada', nivel: 'C', definitividad: 'Interina', estimulos: 'Estímulo Equivalente a PRIDE B', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctor en Filosofía de la Ciencia por la UNAM, FFyL
Maestro en Filosofía de la Ciencia por la UNAM, FFyL
Biólogo por la UNAM, Facultad de Ciencias', correo: '', telefono: '5623-0222', extension:'42821', humanindex: '', foto: '23SFGuerrero.jpg')
Investigador.create(email: 'aleidahc@unam.mx', password: '123456', programa_id: '10', nombres: 'Aleida', apPat: 'Hernández', apMat: 'Cervantes', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Estímulo Equivalente a PRIDE B', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Derecho y Sociedad', historiaAcademica: 'Doctora en Derecho, Facultad de Derecho, UNAM
Maestra en Derecho, Facultad de Derecho, UNAM
Licenciada Facultad de Derecho y Ciencias Sociales, UAS', correo: '', telefono: '56-23-02-22', extension:'42823', humanindex: '', foto: '24AHernandez.jpg')
Investigador.create(email: 'levjardon@ciencias.unam.mx', password: '123456', programa_id: '2', nombres: 'Lev Orlando', apPat: 'Jardón', apMat: 'Barbolla', nombramiento: 'Investigador', categoria: 'Asociado', nivel: 'C', definitividad: 'Interino', estimulos: 'Estímulo Equivalente a PRIDE B', sociedades: 'Candidato al Sistema Nacional de Investigadores', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: '', correo: '', telefono: '56230222', extension:'42771', humanindex: '', foto: '25LOJardon.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '26MEEJarquin.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '27JVJuarez.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '28EKoppen.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '29AMLeal.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '30MdCLegorreta.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '31LLoeza.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '32PLopez.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '33JLopez.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '34RLopez.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '35EMMaass.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '36RLMansilla.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '37GTMateos.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '38JFMorales.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '39RAMorales.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '40JMunoz.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '41ANegrete.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '42SNiccolai.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '43TOrdorika.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '44OQuesada.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '45MdlPRamos.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '46MSanchez.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '47JSaxe.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '48OTena.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '49GValencia.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '50MAVega.jpg')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')