Investigador.create(email: 'aguiluz@unam.mx', password:'duar48', programa_id: '3', nombres: 'Maya Victoria', apPat: 'Aguiluz', apMat: 'Ibargüen', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Ciencias Sociales, Facultad Latinoamericana de Ciencias Sociales
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM ', correo: 'mayaguiluz@hotmail.com', telefono: '5623-0202', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AUIM611025', foto:'1MVAguiluz.jpg')
Investigador.create(email: 'mareugalv@gmail.com', password: 'fuuf7', programa_id: '10', nombres: 'María Eugenia', apPat: 'Alvarado', apMat: 'Rodríguez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Derecho y Sociedad', historiaAcademica: 'Doctora en Pedagogía, Facultad de Filosofía y Letras, UNAM
Maestra en Pedagogía, Facultad de Filosofía y Letras, UNAM
Licenciada en Pedagogía, Facultad de Filosofía y Letras, UNAM', correo: 'alvarad@unam.mx ', telefono: '5623-0438', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AARE571121', foto: '2MEAlvarado.jpg')
Investigador.create(email: 'lalvarez@unam.mx', password: 'rsMri93', programa_id: '6', nombres: 'Lucía', apPat: 'Álvarez', apMat: 'Enríquez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II
Miembro de la Red Mexicana de Investigadores sobre Sociedad Civil (Remisoc)', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0424', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AAEL571110', foto: '3LAlvarez.jpg')
Investigador.create(email: 'j.antonio.amoz@gmail.com', password: 'ther59', programa_id: '4', nombres: 'José Antonio', apPat: 'Amozurrutia', apMat: 'de María y Campos', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Cibercultura y Desarrollo de Comunidades de Conocimiento', historiaAcademica: 'Doctor en Sociología, Universidad de Zaragoza, España
Maestro en Sociología, Universidad de Zaragoza, España
Ingeniero Químico, Universidad Iberoamericana', correo: '', telefono: '5623-0222', extension:'42763', humanindex: '', foto: '4JAAmozurrutia.jpg')
Investigador.create(email: 'blazquez@unam.mx', password: 'losBu99', programa_id: '2', nombres: 'Norma', apPat: 'Blazquez', apMat: 'Graf', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctora en Filosofía, Facultad de Filosofía y Letras, UNAM
Maestra en Ciencias, Especialidad en Fisiología y Biofísica, Centro de Investigación y Estudios Avanzados, IPN
Licenciada en Psicología, Universidad Anáhuac', correo: '', telefono: '5623-0222', extension:'42767', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=BAGN560906', foto: '5NBlazquez.jpg')
Investigador.create(email: 'unam.cabrera@gmail.com', password: 'Xinia51', programa_id: '3', nombres: 'Gloria Patricia', apPat: 'Cabrera', apMat: 'López', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Literatura, Facultad de Filosofías y Letras, UNAM
Estudios de Sociología de la literatura en la École de Hautes Études en Sciences Sociales, de París, y de Semiótica en la Università degli Studi, de Bolonia
Licenciada en Lengua y Literaturas Hispánicas, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0447', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=CALG520412', foto: '6GPCabrera.jpg')
Investigador.create(email: 'cadenaroa@gmail.com', password: 'WsonP81', programa_id: '8', nombres: 'Gerardo Jorge', apPat: 'Cadena', apMat: 'Roa', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel III
Miembro Regular de la Academia Mexicana de Ciencias
Miembro de la Junta de Gobierno de la UNAM', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctor en Sociología, Universidad de Wisconsin-Madison, USA
Maestro en Sociología, Universidad de Wisconsin-Madison, USA
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0442', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=CARG570709', foto: '7GJCadena.jpg')
Investigador.create(email: 'marthap@unam.mx', password: 'ldSlas85', programa_id: '9', nombres: 'Martha Patricia', apPat: 'Castañeda', apMat: 'Salgado', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa Investigación Feminista', historiaAcademica: 'Doctora en Antropología, Instituto de Investigaciones Antropológicas, UNAM
Maestra en Antropología Social, Universidad Iberoamericana
Licenciada en Antropología, Universidad Autónoma de Puebla', correo: '', telefono: '5623-0222', extension:'42764', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=%20CASM631014', foto: '8MPCastaneda.jpg')
Investigador.create(email: 'elvira.concheiro@gmail.com', password: 'aqlos62', programa_id: '5', nombres: 'María Elvira', apPat: 'Concheiro', apMat: 'Bórquez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestría en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42779', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=COBE541016', foto: '9MEConcheiro.jpg')
Investigador.create(email: 'molotla.cf@unam.mx', password: 'Aeid57', programa_id: '7', nombres: 'Felipe', apPat: 'Contreras', apMat: 'Molotla', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Por Artículo 51', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel B', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación La Producción de Bienes y Servicios Básicos', historiaAcademica: 'Doctor en Estudios de Población, El Colegio de México
Maestro en Población, Facultad Latinoamericana de Ciencias Sociales, Sede Académica México
Licenciado en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0263', extension:'', humanindex: '', foto: '10FContreras.jpg')
Investigador.create(email: 'consuar@unam.mx', password: 'Aiiid31', programa_id: '7', nombres: 'Enrique', apPat: 'Contreras', apMat: 'Suárez', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación La Producción de Bienes y Servicios Básicos', historiaAcademica: 'Doctor en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestro en Ciencias Sociales, Facultad Latinoamericana de Ciencias Sociales, Santiago de Chile
Licenciado en Ciencias Sociales, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0261', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=COSE410224', foto: '11EContreras.jpg')
Investigador.create(email: 'correas@unam.mx', password: 'avioAn94', programa_id: '10', nombres: 'Oscar', apPat: 'Correas', apMat: 'Vázquez', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel III', adscripcion: 'Programa de investigación Drecho y Sociedad', historiaAcademica: 'Doctor en Derecho,Universidad de Saint Etienne, Francia
Maestro en Ciencias Sociales, Facultad de Filosofía y Letras, Universidad Autónoma de Puebla
Licenciado en Derecho, Universidad Católica de Córdoba', correo: '', telefono: '', extension:'', humanindex: '', foto: '12OCorreas.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '13SLDaville.jpg')

Investigador.create(email: 'jose@delval1.com', password: 'anTa65', programa_id: '8', nombres: 'José Manuel', apPat: 'Del Val', apMat: 'Blanco', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: '', sociedades: '', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Licenciado en Etnología, Escuela Nacional de Antropología e Historia', correo: '', telefono: '', extension:'', humanindex: '', foto: '14JMDelVal.jpg')
Investigador.create(email: 'giandelgado@unam.mx', password: 'Prez66', programa_id: '6', nombres: 'Gian Carlo', apPat: 'Delgado', apMat: 'Ramos', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctor en Ciencias Ambientales, Universidad Autónoma de Barcelona, España
Maestro en Economía Ecológica y Gestión Ambiental, Universidad Autónoma de Barcelona, España
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0222', extension:'42777', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=DERG780608', foto: '15GCDelgado.jpg')
Investigador.create(email: 'estradaalbateresa52@gmail.com', password: '0fdg4', programa_id: '3', nombres: 'Alba Teresa', apPat: 'Estrada', apMat: 'Castañón', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Ciencia Social con Especialidad en Sociología, El Colegio de México
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0477', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=EACA511030', foto: '16ATEstrada.jpg')
Investigador.create(email: 'dfavelag@unam.mx', password: 'Caro71', programa_id: '8', nombres: 'Diana Margarita', apPat: 'Favela', apMat: 'Gavia', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencia Política, Universidad de Tulane, USA
Maestra en Economía Política Internacional, Centro de Investigación y Docencia Económicas, A. C.
Maestra en Ciencia Política, Universidad de Tulane, USA
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '2014mf02@gmail.com', telefono: '5623-0421', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=FAGD590416', foto: '17DMFavela.jpg')
Investigador.create(email: 'vfloresolea@gmail.com', password: 'sAlvar96', programa_id: '5', nombres: 'Víctor', apPat: 'Flores', apMat: 'Olea', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: '', estimulos: '', sociedades: '', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Estudios de Doctorado en Ciencias Políticas, Escuela Práctica de Altos Estudios, París
Licenciado en Derecho, Facultad de Derecho, UNAM', correo: '', telefono: '5623-0264', extension:'', humanindex: '', foto: '18VFlores.jpg')
Investigador.create(email: 'olivgall@unam.mx', password: 'Idff11', programa_id: '8', nombres: 'Olivia Joanna', apPat: 'Gall', apMat: 'Sonabend', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II
Miembro de la Academia Mexicana de Ciencias', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencia Política, Institut d’ Ètudes Politiques de Grenoble, Francia
Maestra en Ciencia Política, Institut d’ Ètudes Politiques de Grenoble, Francia
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42775', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GASO561021', foto: '19OGall.jpg')
Investigador.create(email: 'joseg@unam.mx', password: 'iana44', programa_id: '5', nombres: 'José Guadalupe', apPat: 'Gandarilla', apMat: 'Salgado', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Doctor en Filosofía Política, Universidad Autónoma Metropolitana-Iztapalapa
Maestro en Estudios Latinoamericanos, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0222', extension:'42766', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GASG671212', foto: '20JGGandarilla.jpg')
Investigador.create(email: 'tzolkin4@unam.mx', password: 'iuD5tr', programa_id: '4', nombres: 'Jorge Alejandro', apPat: 'González', apMat: 'Sánchez', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel III', adscripcion: 'Programa de Investigación Cibercultura y Desarrollo de Comunidades de Conocimiento', historiaAcademica: 'Doctor en Ciencias Sociales, Universidad Iberoamericana
Maestro en Sociología, Universidad Iberoamericana
Licenciado en Comunicación, Universidad Iberoamericana', correo: 'jorge@labcomplex.net', telefono: '5623-0449', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GOSJ541129', foto: '21JAGonzalez.jpg')
Investigador.create(email: 'guillermo.guajardo@unam.mx', password: 'fD9th', programa_id: '2', nombres: 'Guillermo Agustín', apPat: 'Guajardo', apMat: 'Soto', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Maestro en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Licenciado en Historia, Facultad de Filosofía y Humanidades, Universidad de Chile', correo: '', telefono: '5623-0431', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GUSG620619', foto: '22GAGuajardo.jpg')
Investigador.create(email: 'FabrizzioMc@gmail.com', password: '34Mus', programa_id: '1', nombres: 'Siobhan Fenella', apPat: 'Guerrero', apMat: 'Mc Manus', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Estímulo Equivalente a PRIDE C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctor en Filosofía de la Ciencia por la UNAM, FFyL
Maestro en Filosofía de la Ciencia por la UNAM, FFyL
Biólogo por la UNAM, Facultad de Ciencias', correo: 'siobhanfgm@gmail.com', telefono: '5623-0222', extension:'42821', humanindex: '', foto: '23SFGuerrero.jpg')
Investigador.create(email: 'aleidahc@unam.mx', password: 'fg86', programa_id: '10', nombres: 'Aleida', apPat: 'Hernández', apMat: 'Cervantes', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Estímulo Equivalente a PRIDE C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Derecho y Sociedad', historiaAcademica: 'Doctora en Derecho, Facultad de Derecho, UNAM
Maestra en Derecho, Facultad de Derecho, UNAM
Licenciada Facultad de Derecho y Ciencias Sociales, UAS', correo: 'aleycristal@hotmail.com', telefono: '56-23-02-22', extension:'42823', humanindex: '', foto: '24AHernandez.jpg')
Investigador.create(email: 'levjardon@ciencias.unam.mx', password: '75fgfg', programa_id: '2', nombres: 'Lev Orlando', apPat: 'Jardón', apMat: 'Barbolla', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Estímulo Equivalente a PRIDE C', sociedades: 'Candidato al Sistema Nacional de Investigadores', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctorado en Ciencias Biomédicas, UNAM
Licenciado en Biología, UNAM', correo: 'levjardon@yahoo.com.mx', telefono: '56230222', extension:'42771', humanindex: '', foto: '25LOJardon.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '26MEEJarquin.jpg')

Investigador.create(email: 'jjuarez@unam.mx', password: 'wedh67', programa_id: '8', nombres: ' Julio Vicente', apPat: 'Juárez', apMat: 'Gámiz', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Maestro y Doctor en Comunicación Política, Universidad de Sheffield, United Kingdom
Licenciado en Psicología, Facultad de Psicología, UNAM', correo: '', telefono: '5623-0222', extension:'42776', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=JUGJ730817', foto: '27JVJuarez.jpg')
Investigador.create(email: 'koppen@unam.mx', password: 'vbnF5', programa_id: '11', nombres: 'Elke', apPat: 'Koppen', apMat: 'Prubmann', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Estudios Visuales', historiaAcademica: 'Doctora en Bibliotecología y Estudios de la Información, Facultad de Filosofía y Letras, UNAM
Maestra en Bibliotecología, Facultad de Filosofía y Letras, UNAM
Licenciada en Sociología, Universidad de Bielefeld, Alemania', correo: 'elke.koppen@gmail.com', telefono: '5623-0433', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=KOPE531130', foto: '28EKoppen.jpg')
Investigador.create(email: 'alejandraleal@gmail.com ', password: 'jmn09', programa_id: '6', nombres: 'Alejandra María', apPat: 'Leal', apMat: 'Leal', nombramiento: 'Investigadora', categoria: 'Asociada', nivel: 'C', definitividad: 'Interina', estimulos: 'Estímulos Equivalente a PRIDE B y PEI', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Antropología Sociocultural, Universidad de Columbia, Nueva York
Maestra en Antropología Sociocultural, New School for Social Research, Nueva York
Licenciada en Historia, Universidad Nacional Autónoma de México', correo: '', telefono: '', extension:'', humanindex: '', foto: '29AMLeal.jpg')
Investigador.create(email: 'clegorreta@unam.mx', password: 'jhs34', programa_id: '8', nombres: 'María del Carmen', apPat: 'Legorreta', apMat: 'Díaz', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en "Ètudes sur l’ Amérique Latine", Université Toulouse Le-Mirail, Francia
Maestra en Ciencias del Desarrollo Rural Regional, Universidad Autó­noma de Chapingo
Licenciada en Sociología, Facultad de Ciencias Políticas Sociales, UNAM', correo: '', telefono: '5623-0412', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=LEDC601030', foto: '30MdCLegorreta.jpg')
Investigador.create(email: 'loezar@unam.mx', password: 'lkGP9', programa_id: '6', nombres: 'Laura', apPat: 'Loeza', apMat: 'Reyes', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Ciencia Política, Universidad de París I, Panthéon-Sorbonne
Maestra en Sociología Política, Instituto de Investigaciones Dr. José María Luis Mora
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42765', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=LORL611021', foto: '31LLoeza.jpg')
Investigador.create(email: 'paulapezca@unam.mx', password: 'QfW09', programa_id: '8', nombres: 'Paula', apPat: 'López', apMat: 'Caballero', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Antropología Social y Etnología, École des Hautes Études en Sciences Sociales, París, Francia
Maestra en Antropología Social y Etnología, École des Hautes Études en Sciences Sociales, París, Francia
Licenciada en Historia, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0222', extension:'42807', humanindex: '', foto: '32PLopez.jpg')
Investigador.create(email: 'jahellg1973@yahoo.com.mx', password: 'rxri7', programa_id: '9', nombres: 'Jahel', apPat: 'López', apMat: 'Guerrero', nombramiento: 'Investigadora', categoria: 'Asociada', nivel: 'C', definitividad: 'Interina', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Feminista', historiaAcademica: 'Doctora en Antropología, Facultad de Filosofía y Letras/Instituto de investigaciones Antropológicas, UNAM
Maestra en Antropología Social, Centro de Investigaciones y Estudios Superiores en Antropología Social, México
Licenciada en Etnología, Escuela Nacional de Antropología e Historia', correo: '', telefono: '5623-0264', extension:'', humanindex: '', foto: '33JLopez.jpg')
Investigador.create(email: 'rosalial@unam.mx', password: 'Maell', programa_id: '7', nombres: 'Rosalía', MaellapPat: 'López', apMat: 'Paniagua', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación La producción de Bienes y Servicios Básicos', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Sociología Política, Instituto Dr. José María Luis Mora
Licenciada en Sociología, Escuela Nacional de Estudios Profesionales Aragón, UNAM', correo: '', telefono: '', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=LOPR570411', foto: '34RLopez.jpg')
Investigador.create(email: 'mmaass@unam.mx', password: 'naeYos', programa_id: '4', nombres: 'Elisa Margarita', apPat: 'Maass', apMat: 'Moreno', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Cibercultura y Desarrollo de Comunidades de Conocimiento', historiaAcademica: 'Doctora en Ciencias Sociales, Universidad Iberoamericana
Maestra en Comunicación, Universidad Iberoamericana
Licenciada en Conservación y Restauración de Bienes Muebles, Instituto Nacional de Antropología e Historia
Curso la Licenciatura en Historia, Facultad de Filosofía y Letras, UNAM', correo: 'margarita_maass@yahoo.com.mx', telefono: '5623-0222', extension:'42805', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=MAME580722', foto: '35EMMaass.jpg')
Investigador.create(email: 'mansy@unam.mx', password: 'T%Eev', programa_id: '2', nombres: 'Ricardo Lino', apPat: 'Mansilla', apMat: 'Corona', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Matemáticas, Universidad de La Habana, Cuba
Master of Arts in Economics, University of Carleton, Canadá
Licenciado en Matemáticas, Facultad de Ciencias, Universidad de La Habana, Cuba', correo: '', telefono: '5623-0435', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/pagina/pagina_inicio.php?rfc=MACR550923', foto: '36RLMansilla.jpg')
Investigador.create(email: 'gisela.mateos@unam.mx', password: 'si56cSe', programa_id: '1', nombres: 'Gisela Tamhara', apPat: 'Mateos', apMat: 'González', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctora en Historia de la Ciencia, Universidad Autónoma de Barcelona, España
Maestra en Historia de la Ciencia, Universidad Autónoma de Barcelona, España
Física, Facultad de Ciencias, UNAM', correo: '', telefono: '5623-0265', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=MAGG660718', foto: '37GTMateos.jpg')
Investigador.create(email: 'jfmoralesb@gmail.com', password: 'ossm09', programa_id: '6', nombres: 'José Federico', apPat: 'Morales', apMat: 'Barragán', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctor en Ecología y Desarrollo Sostenible, El Colegio de la Frontera Sur
Maestro en Ciencias Económicas, UNAM
Licenciado en Economía, UNACH', correo: '', telefono: '5623 0022', extension:'42792', humanindex: '', foto: '38JFMorales.jpg')
Investigador.create(email: 'rsarabia@unam.mx', password: 'ares', programa_id: '1', nombres: 'Rosa Angélica', apPat: 'Morales', apMat: 'Sarabia', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores I', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctora en Historia, Facultad de Filosofía y Letras, UNAM
Maestra en Historia, Universidad Iberoamericana
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0450', extension:'', humanindex: '', foto: '39RAMorales.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '40JMunoz.jpg')

Investigador.create(email: 'aqny@unam.mx', password: 'siM7', programa_id: '2', nombres: 'Aquiles', apPat: 'Negrete', apMat: 'Yankelevich', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Comunicación Científica, Universidad de Bath, Reino Unido
Maestro en Manejo de Recursos Naturales, Universidad de Edimburgo, Reino Unido
Licenciado en Biología, Facultad de Ciencias, UNAM
Especialidad en Ciencias de la Computación, Fundación Arturo Rosenblueth', correo: '', telefono: '5623-0444', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=NEYA660816', foto: '41ANegrete.jpg')
Investigador.create(email: 'snicco@colmex.mx', password: 'el6M', programa_id: '1', nombres: 'Sergio', apPat: 'Niccolai', apMat: 'Salvadori', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: '', sociedades: '', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctorado en Historia de las Américas (DR, PhD), Universidad de los Estudios de Génova, Italia
Maestro en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Laurea de Doctor en Filosofía (DL, MD - antigua titulación), Universidad de los Estudios de Pisa, Italia', correo: '', telefono: '5623-0271', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=NISS600517', foto: '42SNiccolai.jpg')
Investigador.create(email: 'teresaos@unam.mx', password: 'alin#', programa_id: '9', nombres: 'Teresa', apPat: 'Ordorika', apMat: 'Sacristán', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores I', adscripcion: 'Programa Investigación Feminista', historiaAcademica: 'Doctora en Sociología, University of London
Maestra en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0429', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=NISS600517', foto: '43TOrdorika.jpg')
Investigador.create(email: 'oquesada@unam.mx', password: 'sios8', programa_id: '11', nombres: 'Octavio', apPat: 'Quesada', apMat: 'García', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel A', sociedades: 'Sistema Nacional de Investigadores Nivel I', adscripcion: 'Programa de Investigación Estudios Visuales', historiaAcademica: 'Doctor en Ciencias Biomédicas (Neuroquímica), Facultad de Medicina / Instituto de Fisiología Celular, UNAM
Maestro en Investigación Biomédica Básica, UACPyP del CCH / Instituto de Fisiología Celular, UNAM
Biólogo, Facultad de Ciencias, UNAM', correo: '', telefono: '5623-0270', extension:'', humanindex: '', foto: '44OQuesada.jpg')
Investigador.create(email: 'ramoslm@unam.mx', password: '12nar', programa_id: '2', nombres: 'María de la Paz', apPat: 'Ramos', apMat: 'Lara', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctora en Historia, Facultad de Filosofía y Letras, UNAM
Maestra en Ciencias Físicas, Facultad de Ciencias, UNAM
Física, Facultad de Ciencias, UNAM', correo: '', telefono: '5623-0430', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=RALP620124', foto: '45MdlPRamos.jpg')
Investigador.create(email: 'menchero@unam.mx', password: 'de5vi', programa_id: '11', nombres: 'Mauricio', apPat: 'Sánchez', apMat: 'Menchero', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Estudios Visuales', historiaAcademica: 'Maestro y Doctor en Historia y Comunicación en el Mundo Contemporáneo, Facultad de Ciencias de la Información, Universidad Complutense de Madrid, España
Licenciado en Ciencias de la Comunicación Social, Universidad Autónoma Metropolitana-Xochimilco', correo: '', telefono: '5623-0222', extension:'42778', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=SAMM620704', foto: '46MSanchez.jpg')
Investigador.create(email: 'saxe@unam.mx', password: 'S4x3F', programa_id: '5', nombres: 'John', apPat: 'Saxe', apMat: 'Fernández', nombramiento: 'Profesor', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel ', sociedades: 'Sistema Nacional de Investigadores nivel III', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Doctor en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Maestro en Estudios Latinoamericanos, Universidad de Washington, St. Louis Missouri, USA
Licenciado en Ciencia Política, Universidad de Brandeis, Waltham Massachussets', correo: '', telefono: '5623-0198', extension:'', humanindex: '', foto: '47JSaxe.jpg')
Investigador.create(email: 'tena@unam.mx', password: 'OP8d', programa_id: '9', nombres: 'Olivia', apPat: 'Tena', apMat: 'Guerrero', nombramiento: 'Profesora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Feminista', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Psicología: Metodología de la Investigación Teórica y Conduc­tual, Facultad de Estudios Superiores Iztacala, UNAM
Licenciada en Psicología, Facultad de Estudios Superiores Iztacala, UNAM', correo: '', telefono: '5623-0222', extension:'42761', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=TEGO590105', foto: '48OTena.jpg')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '49GValencia.jpg')

Investigador.create(email: 'aimeevegamx@yahoo.com.mx', password: 'ar9rio', programa_id: '9', nombres: 'Medley Aimeé', apPat: 'Vega', apMat: 'Montiel', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Feminista', historiaAcademica: 'Doctora en Periodismo y Ciencias de la Comunicación, Universidad Autónoma de Barcelona
Maestra en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM
Máster en Periodismo y Ciencias de la Comunicación, Universidad Autónoma de Barcelona
Licenciada en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-2300', extension:'42774', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=VEMM740303', foto: '50MAVega.jpg')

Investigador.create(email: 'ayari.pasquier@unam.mx', password: '123456', programa_id: '6', nombres: 'Ayari', apPat: 'Pasquier', apMat: 'Merino', nombramiento: 'Investigadora', categoria: 'Asociada', nivel: 'C', definitividad: 'Por Artículo 51', estimulos: '', sociedades: 'Candidata al Sistema Nacional de Investigadores', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Ciencias Sociales (Sociología), Centro de Estudios Sociológicos, Colegio de México
Maestra en Antropología, Alma Mater Studiorum, Università Di Bologna
Licenciada en Comunicación Social, Universidad Autónoma Metropolitana-Xochimilco ', correo: 'ayaripasquier@gmail.com', telefono: '', extension:'', humanindex: '', foto: '')

Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')
Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')