Tecnico.create(email: 'alegre@unam.mx', password: 'offy26', nombres: 'María de los Ángeles Consuelo', apPat: 'Alegre', apMat: 'Schettino', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Maestría en Diseño y Comunicación Visual, Facultad de Artes y  Diseño, UNAM
Licenciada en Diseño Gráfico, Escuela Nacional de Artes Plásticas, UNAM', correo: '', telefono: '5623-0222', extension:'42063', humanindex: '', foto: '1MdlACAlegre.jpg')
Tecnico.create(email: 'carrillopatricia4@gmail.com', password: 'ieF27', nombres: 'Lucía Patricia', apPat: 'Carrillo', apMat: 'Velázquez', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencias de la Administración, Facultad de Contaduría y Administración, UNAM
Investigación Posdoctoral, Investigación Científica Básica SEP-CONACyT
Maestra en Administración de Organizaciones, Facultad de Contaduría y Administración, UNAM
Ingeniera en Computación, Facultad de Ingeniería, UNAM', correo: 'carrillopaty@hotmail.com', telefono: '5623-0222', extension:'42808', humanindex: 'humanindex.unam.mx/humanindex/pagina/pagina_inicio_tecnicos.php?rfc=CAVL620501', foto: '2LPCarrillo.jpg')
Tecnico.create(email: 'casale@unam.mx', password: 'ern$ad67', nombres: 'Concepción Alida', apPat: 'Casale', apMat: 'Núñez ', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Maestra en Psicoterapia Psicoanalítica, Centro ELEIA
Matemática, Facultad de Ciencias, UNAM', correo: '', telefono: '5623-0222', extension:'42061', humanindex: '', foto: '3CACasale.jpg')
Tecnico.create(email: 'clarae@unam.mx', password: 'Aerto86', nombres: 'Clara Elizabeth', apPat: 'Castillo', apMat: 'Álvarez', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Estudiante de la Maestría en Historia del Arte, Facultad de Filosofía y Letras, UNAM
Licenciada en Periodismo, Escuela de Periodismo Carlos Septién García', correo: '', telefono: '5623-0222', extension:'42060', humanindex: '', foto: '4CECastillo.jpg')
Tecnico.create(email: 'mgcg@unam.mx', password: 'rEfdgs63', nombres: 'María Gladys de Guadalupe', apPat: 'Castillo', apMat: 'Guerrero', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Por artículo 51', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Difusión', historiaAcademica: 'Contadora Pública, Universidad Autónoma del Sudeste, Campeche', correo: '', telefono: '5623-0222', extension:'42804', humanindex: '', foto: '5MGCastillo.jpg')
Tecnico.create(email: 'amanali.cv@gmail.com', password: 'nalei74', nombres: 'Amanali María', apPat: 'Cornejo', apMat: 'Vázquez', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'B', definitividad: 'Interina', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel B', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '6AMCornejo.jpg')
Tecnico.create(email: 'clausrio@unam.mx', password: 'noD46', nombres: 'Claudia Gabriela', apPat: 'del Río', apMat: 'Rodríguez', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencias de Desarrollo Rural Regional, Universidad Autónoma Chapingo
Maestra en Comunicación de la Facultad de Ciencias Políticas y Sociales-UNAM
Licenciada en Sociología, UAM', correo: '', telefono: '5623-0269', extension:'', humanindex: '', foto: '7CGDelRio.jpg')
Tecnico.create(email: 'gustavoe@unam.mx', password: 'dhg06', nombres: 'Gustavo', apPat: 'Enríquez', apMat: 'Téllez', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Información y Documentación', historiaAcademica: 'Licenciado en Biblioteconomía, Escuela Nacional de Biblioteconomía y Archivonomía', correo: '', telefono: '5623-0445', extension:'', humanindex: '', foto: '8GEnriquez.jpg')
Tecnico.create(email: 'villela@unam.mx', password: 'elJ5es64', nombres: 'Carlos Arturo', apPat: 'Flores', apMat: 'Villela', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Estudios Visuales', historiaAcademica: 'Maestro en Historia del Arte, Facultad de Filosofía y letras, UNAM
Licenciado en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0422', extension:'', humanindex: '', foto: '9CAFlores.jpg')
Tecnico.create(email: 'mhgb@unam.mx', password: 'An5fgC51', nombres: 'María Haydeé', apPat: 'García', apMat: 'Bravo', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Maestra en Antropología Social, Escuela Nacional de Antropología e Historia
Maestra en Historia y Patrimonio, Master Erasmus Mundus TPTI, Universidad Paris 1 Pantheon-Sorbonne
Licenciada en Ciencias de la Comunicación, Universidad de San Luis Potosí', correo: 'mahaydee@yahoo.com', telefono: '5623-0262', extension:'', humanindex: '', foto: '10MHGarcia.jpg')
Tecnico.create(email: 'lgu@unam.mx', password: 'hf34dh', nombres: 'Leonor', apPat: 'García', apMat: 'Urbano', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Apoyo a la Docencia, Educación Continua y Diplomados', historiaAcademica: 'Maestra en Bibliotecología y Estudios de la Información, Facultad de Filosofía y Letras, UNAM
Licenciada en Bibliotecología, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0417', extension:'', humanindex: '', foto: '11LGarcia.jpg')
Tecnico.create(email: 'jfjimc@unam.mx', password: 'siu98', nombres: 'Josefina', apPat: 'Jiménez', apMat: 'Cortés', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Pasante de la Licenciatura en Letras Hispanoamericanas, Universidad Autónoma Metropolitana Iztapalapa', correo: '', telefono: '5623-0222', extension:'42063', humanindex: '', foto: '12JJimenez.jpg')
Tecnico.create(email: 'labrador@unam.mx', password: 'fghP9', nombres: 'Alejandro', apPat: 'Labrador', apMat: 'Sánchez', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'C', definitividad: 'Interino', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Estudios de Maestría en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Licenciado en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0434', extension:'', humanindex: '', foto: '13ALabrador.jpg')
Tecnico.create(email: 'mrlt@unam.mx', password: 'hJH98', nombres: 'Rogelio', apPat: 'López', apMat: 'Torres', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Estudios de Doctorado en Fisiología y Biofísica, Centro de Investigación y Estudios Avanzados, IPN
Maestría en Ciencias en Fisiología y Biofísica, Centro de Investigación y Estudios Avanzados, IPN
Egresado de la Facultad de Medicina, UNAM', correo: '', telefono: '5623-0222', extension:'42773', humanindex: '', foto: '14RLopez.jpg')
Tecnico.create(email: 'brissa@unam.mx', password: 'iesp3s', nombres: 'Brisa Jessica', apPat: 'Luna', apMat: 'Sabás', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Cómputo', historiaAcademica: '', correo: '', telefono: '5623-0207', extension:'', humanindex: '', foto: '15BJLuna.jpg')
Tecnico.create(email: 'victormm@unam.mx', password: 's6mvi', nombres: 'Víctor Manuel', apPat: 'Méndez', apMat: 'Villanueva', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: '', adscripcion: 'Departamento de Producción Audiovisual y Multimedia', historiaAcademica: 'Licenciado en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0206', extension:'', humanindex: '', foto: '16VMMendez.jpg')
Tecnico.create(email: 'tzunum13@gmail.com', password: 'es3se', nombres: 'Dora Evangelina', apPat: 'Mendizábal', apMat: 'García', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Interina', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Maestra en Ciencias Sociales, Centro de Investigaciones y Estudios Superiores en Antropología Social, CIESAS Centro
Licenciada en Ciencias Jurídicas y Sociales, Universidad de San Carlos de Guatemala', correo: '', telefono: '', extension:'', humanindex: '', foto: '17DEMendizabal.jpg')
Tecnico.create(email: 'romanero@unam.mx', password: 'ev8Se', nombres: 'Rosa María', apPat: 'Mendoza', apMat: 'Rosas', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Candidata a la Maestría en Geografía con Orientación en Territorio y Sociedad, Facultad de Filosofía y Letras, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42806', humanindex: '', foto: '18RMMendoza.jpg')
Tecnico.create(email: 'hmendoza@unam.mx', password: 'ar8es', nombres: 'Hermelinda', apPat: 'Villavicencio', apMat: 'Mendoza', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa Investigación Feminista', historiaAcademica: 'Créditos de la Maestría en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0446', extension:'', humanindex: '', foto: '19HMendoza.jpg')
Tecnico.create(email: 'moncadal@unam.mx', password: 'i5ase', nombres: 'Alma Laura', apPat: 'Moncada', apMat: 'Marín', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Maestra en Bibliotecología y Estudios de la Información, Facultad de Filosofía y Letras, UNAM
Licenciada en Comunicación y Periodismo Colectivo, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0432', extension:'', humanindex: '', foto: '20ALMoncada.jpg')
Tecnico.create(email: 'zafra@unam.mx', password: 'ioad', nombres: 'Liliana Josefina', apPat: 'Muñiz', apMat: 'Zafra', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Cómputo', historiaAcademica: 'Maestra en Administración, Facultad de Contaduría y Administración, UNAM
Ingeniera en Computación, Facultad de Ingeniería, UNAM', correo: '', telefono: '5623-0222', extension:'42820', humanindex: '', foto: '21LJMuniz.jpg')
Tecnico.create(email: 'olivera@unam.mx', password: 'spin83', nombres: 'María Elena', apPat: 'Olivera', apMat: 'Córdova', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: '', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Humanidades con línea en Teoría Literaria por la Universidad Autónoma Metropolitana Iztapalapa
Maestra en Literatura Mexicana, Facultad de Filosofía y Letras, UNAM
Licenciada en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0267', extension:'', humanindex: '', foto: '22MEOlivera.jpg')
Tecnico.create(email: 'lolivos@unam.mx', password: 'x23ta', nombres: 'Leonardo Felipe', apPat: 'Olivos', apMat: 'Santoyo', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Feminista', historiaAcademica: 'Programa de posgrado en estudios latinoamericanos
Maestro en Estudios Políticos y Sociales, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciado en Ciencia Política y Administración Pública, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0420', extension:'', humanindex: '', foto: '23LFOlivos.jpg')
Tecnico.create(email: 'nicolasa@unam.mx', password: 'itin3', nombres: 'Nicolasa', apPat: 'Ramírez', apMat: 'Vicente', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Información y Documentación', historiaAcademica: 'Licenciada en Bibliotecología, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0031', extension:'', humanindex: '', foto: '24NRamirez.jpg')
Tecnico.create(email: 'carolashz@gmail.com', password: 'spx6', nombres: 'Carolina', apPat: 'Sánchez', apMat: 'García', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Licenciada en Antropología Social, Escuela Nacional de Antropología e Historia', correo: '', telefono: '', extension:'', humanindex: '', foto: '25CSanchez.jpg')
Tecnico.create(email: 'isauribe@unam.mx', password: 'in4sp', nombres: 'Isauro', apPat: 'Uribe', apMat: 'Pineda', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Licenciado en Diseño de la Comunicación Gráfica, Universidad Autónoma Metropolitana-Xochimilco', correo: '', telefono: '5623-0022', extension:'42061', humanindex: '', foto: '26IUribe.jpg')
Tecnico.create(email: 'paulovazquez@yahoo.com.mx', password: '56nta', nombres: 'Paulo César', apPat: 'Vázquez', apMat: 'Pacheco', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel B', sociedades: '', adscripcion: 'Departamento de Producción Audiovisual y Multimedia', historiaAcademica: 'Licenciado en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42787', humanindex: '', foto: '27PCVazquez.jpg')
Tecnico.create(email: 'visar@unam.mx', password: '2adis', nombres: 'Juan Carlos', apPat: 'Villa', apMat: 'Soto', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Maestro en Economía y Gestión del Cambio Tecnológico, UAM-Xochi­milco
Licenciado en Psicología, Escuela Nacional de Estudios Profesionales-Iztacala, UNAM', correo: '', telefono: '5623-0222', extension:'42770', humanindex: '', foto: '28JCVilla.jpg')
Tecnico.create(email: 'anaelisa30@gmail.com', password: 'it68', nombres: 'Ana Elisa', apPat: 'Villarreal', apMat: 'Barrón', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Por Artículo 51', estimulos: 'Estímulo Equivalente PRIDE B', sociedades: '', adscripcion: 'Apoyo a la Docencia, Educación Continua y Diplomados ', historiaAcademica: 'Pasante de Licenciatura', correo: '', telefono: '5623-0222', extension:'42784', humanindex: '', foto: '29AEVillarreal.jpg')

Tecnico.create(email: '', password: 'C0r73', nombres: 'Mercedes', apPat: 'Cortez', apMat: 'Arriaga', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')
Tecnico.create(email: 'garod@unam.mx', password: 'Gaga66', nombres: 'Humberto', apPat: 'García', apMat: 'Rodríguez', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Planeación y Seguimiento Académico', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')
Tecnico.create(email: 'jorge.pm@ceiich.unam.mx', password: 'ceiich2018', nombres: 'Jorge', apPat: 'Pantaleón', apMat: 'Martínez', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'C', definitividad: 'Por Artículo 51', estimulos: 'Estímulo Equivalente PRIDE B', sociedades: '', adscripcion: 'Departamento de Cómputo', historiaAcademica: 'Maestro en Ingeniería en Computación, Posgrado en Ciencia e Ingeniería de la Computación, UNAM
Ingeniero Computación, Facultad de Ingeniería, UNAM', correo: '', telefono: '5623-0204', extension:'', humanindex: '', foto: '')

