# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Programa.create(nombre: '1 Historia de la ciencia', foto: 'HistoriaCiencia.jpg', descripcion:'Análisis de las condiciones sociales, económicas, políticas y culturales que condicionan la dinámica de la práctica científica, y rescate de las contribuciones más destacadas de las y los científicos mexicanos.')
Programa.create(nombre: '2 Ciencia y Tecnología', foto: 'CienciaTecnologia.jpg', descripcion:'Estudios filosóficos, sociales, económicos, políticos y culturales de la ciencia y la tecnología desde diferentes perspectivas críticas buscando una mayor integración del conocimiento, así como nuevas posibilidades de generación, comunicación y desarrollo de estas actividades.')
Programa.create(nombre: '3 Ciencias Sociales y Literatura', foto: 'SocialesLiteratura.jpg', descripcion:'Contribución a la discusión plural y a la producción de conocimiento sobre enfoques, dominios de estudio y teorías de las ciencias sociales y la literatura, haciendo énfasis en la reflexión y la investigación de problemas actuales en ambos campos.')
Programa.create(nombre: '4 Cibercultura y Desarrollo de Comunidades de Conocimiento', foto: 'Cibercultura.jpg', descripcion:'Investigación de las condiciones en que la comunicación e información se vinculan a la generación y distribución social del conocimiento.')
Programa.create(nombre: '5 El Mundo en el Siglo XXI', foto: 'MundoSXXI.jpg', descripcion:'Analiza los principales retos y oportunidades civilizatorias que enfrenta la humanidad, en particular México y América Latina, a partir de estudiar teórica y empíricamente, las dinámicas actuales del capitalismo, sus contradicciones y los procesos de resistencia social y construcción de alternativas.')
Programa.create(nombre: '6 Ciudades, Gestión, Territorio y Ambiente', foto: 'CiudadesAmbiente.jpg', descripcion:'Estudio de las grandes ciudades del mundo actual como núcleos centrales de agrupamiento humano y como principales centros articuladores del desarrollo económico y social. Incluye la reflexión de la gestión, la vida urbana, así como los intereses y necesidades de los distintos actores y agentes que coexisten en las ciudades contemporáneas.')
Programa.create(nombre: '7 La Producción de Bienes y Servicios Básicos', foto: 'BienesServicios.jpg', descripcion:'Estudio de experiencias innovadoras locales, sectoriales y de programas compensatorios que sirvan para el diseño de políticas sociales duraderas en términos éticos, económicos, sociales, administrativos y ambientales.')
Programa.create(nombre: '8 Poder, Subjetividad y Cultura', foto: 'PoderSubjetividad.jpg', descripcion:'Estudio de los aspectos sociales, económicos, políticos y culturales relevantes para entender los problemas relacionados con los procesos de democratización y desarrollo.')
Programa.create(nombre: '9 Investigación Feminista', foto: 'Feminista.jpg', descripcion:'Incorporación de las propuestas teóricas y epistemológicas del feminismo contemporáneo a la investigación y la docencia con un enfoque interdisciplinario. Generación de conocimientos en diferentes disciplinas y problemas de investigación desde la perspectiva de género.')
Programa.create(nombre: '10 Derecho y Sociedad', foto: 'DerechoSociedad.jpg', descripcion:'Estudio del derecho como fenómeno social que permite explicar el ejercicio del poder, con la posibilidad de influir en el pensamiento jurídico contemporáneo, mediante la crítica a la ideología jurídica.')
Programa.create(nombre: '11 Estudios Visuales', foto: 'EstudiosVisuales.jpg', descripcion:'Análisis teórico-metodológico desde una perspectiva interdisciplinaria de las representaciones culturales y sus expresiones visuales.')

Departamento.create(nombre: 'Cómputo', foto: 'Computo.jpg', descripcion: 'Proporciona la infraestructura de equipo de cómputo y comunicaciones (voz y datos), diseña sistemas informáticos y brinda la asesoría necesaria para el desarrollo de las actividades de los Programas de investigación, de la Dirección, las Secretarías y los Departamentos del Centro.')
Departamento.create(nombre: 'Difusión', foto: 'Difusion.jpg', descripcion: 'Respecto a las actividades académicas: de investigación, de educación continua-docencia y educación continua-divulgación.
- Asesora y colabora con el personal académico de investigación y técnico en la organización de las mismas.
- Realiza las acciones necesarias y trabaja de manera colaborativa con los departamentos técnicos y el área administrativa para su desarrollo.
- Lleva a cabo la difusión por los medios de comunicación universitarios tradicionales y digitales.
- Enlace con la Dirección General de Comunicación Social de la UNAM para la realización de entrevistas con medios nacionales e internacionales.')
Departamento.create(nombre: 'Información y Documentación', foto: 'InfyDocu.jpg', descripcion: 'Impulsa el desarrollo de sus colecciones, las difunde y salvaguarda de acuerdo con las necesidades de los Programas de investigación. Proporciona la información bibliográfica y documental de apoyo al trabajo de investigación.')
Departamento.create(nombre: 'Producción Audiovisual y Multimedia', foto: 'Audiovisual.jpg', descripcion: 'Produce materiales audiovisuales que promueven y dan cuenta de la labor académica del CEIICH, como documentales, cápsulas, videos promocionales y multimedia. También coordina la transmisión en vivo de los encuentros académicos y los enlaces vía videoconferencia, así como el diseño y mantenimiento de la página web.')
Departamento.create(nombre: 'Publicaciones', foto: 'Publicaciones.jpg', descripcion: 'Organiza el trabajo de edición de las publicaciones de acuerdo con los lineamientos del programa editorial anual aprobado por el Comité Editorial del Centro. Diseña las portadas e interiores de las publicaciones impresas y en soporte digital, así como los materiales gráficos para la difusión de los encuentros académicos. Supervisa la distribución y venta de las publicaciones del Centro.')

Investigador.create(email: 'aguiluz@unam.mx', password:'duar48', programa_id: '3', nombres: 'Maya Victoria', apPat: 'Aguiluz', apMat: 'Ibargüen', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM<br>
Maestra en Ciencias Sociales, Facultad Latinoamericana de Ciencias Sociales<br>
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM<br>', correo: 'mayaguiluz@hotmail.com', telefono: '5623-0202', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AUIM611025', foto:'1MVAguiluz.jpg')
Investigador.create(email: 'mareugalv@gmail.com', password: 'fuuf7', programa_id: '10', nombres: 'María Eugenia', apPat: 'Alvarado', apMat: 'Rodríguez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Derecho y Sociedad', historiaAcademica: 'Doctora en Pedagogía, Facultad de Filosofía y Letras, UNAM
Maestra en Pedagogía, Facultad de Filosofía y Letras, UNAM
Licenciada en Pedagogía, Facultad de Filosofía y Letras, UNAM', correo: 'alvarad@unam.mx ', telefono: '5623-0438', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AARE571121', foto: '2MEAlvarado.jpg')
Investigador.create(email: 'lalvarez@unam.mx', password: 'rsMri93', programa_id: '6', nombres: 'Lucía', apPat: 'Álvarez', apMat: 'Enríquez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II
Miembro de la Red Mexicana de Investigadores sobre Sociedad Civil (Remisoc)', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0424', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=AAEL571110', foto: '3LAlvarez.jpg')
Investigador.create(email: 'j.antonio.amoz@gmail.com', password: 'ther59', programa_id: '4', nombres: 'José Antonio', apPat: 'Amozurrutia', apMat: 'de María y Campos', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Cibercultura y Desarrollo de Comunidades de Conocimiento', historiaAcademica: 'Doctor en Sociología, Universidad de Zaragoza, España
Maestro en Sociología, Universidad de Zaragoza, España
Ingeniero Químico, Universidad Iberoamericana', correo: '', telefono: '5623-0222', extension:'42763', humanindex: '', foto: '4JAAmozurrutia.jpg')
Investigador.create(email: 'blazquez@unam.mx', password: 'losBu99', programa_id: '2', nombres: 'Norma', apPat: 'Blazquez', apMat: 'Graf', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctora en Filosofía, Facultad de Filosofía y Letras, UNAM
Maestra en Ciencias, Especialidad en Fisiología y Biofísica, Centro de Investigación y Estudios Avanzados, IPN
Licenciada en Psicología, Universidad Anáhuac', correo: '', telefono: '5623-0222', extension:'42767', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=BAGN560906', foto: '5NBlazquez.jpg')
Investigador.create(email: 'unam.cabrera@gmail.com', password: 'Xinia51', programa_id: '3', nombres: 'Gloria Patricia', apPat: 'Cabrera', apMat: 'López', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Literatura, Facultad de Filosofías y Letras, UNAM
Estudios de Sociología de la literatura en la École de Hautes Études en Sciences Sociales, de París, y de Semiótica en la Università degli Studi, de Bolonia
Licenciada en Lengua y Literaturas Hispánicas, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0447', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=CALG520412', foto: '6GPCabrera.jpg')
Investigador.create(email: 'cadenaroa@gmail.com', password: 'WsonP81', programa_id: '8', nombres: 'Gerardo Jorge', apPat: 'Cadena', apMat: 'Roa', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel III
Miembro Regular de la Academia Mexicana de Ciencias
Miembro de la Junta de Gobierno de la UNAM', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctor en Sociología, Universidad de Wisconsin-Madison, USA
Maestro en Sociología, Universidad de Wisconsin-Madison, USA
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0442', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=CARG570709', foto: '7GJCadena.jpg')
Investigador.create(email: 'marthap@unam.mx', password: 'ldSlas85', programa_id: '9', nombres: 'Martha Patricia', apPat: 'Castañeda', apMat: 'Salgado', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa Investigación Feminista', historiaAcademica: 'Doctora en Antropología, Instituto de Investigaciones Antropológicas, UNAM
Maestra en Antropología Social, Universidad Iberoamericana
Licenciada en Antropología, Universidad Autónoma de Puebla', correo: '', telefono: '5623-0222', extension:'42764', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=%20CASM631014', foto: '8MPCastaneda.jpg')
Investigador.create(email: 'elvira.concheiro@gmail.com', password: 'aqlos62', programa_id: '5', nombres: 'María Elvira', apPat: 'Concheiro', apMat: 'Bórquez', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestría en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42779', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=COBE541016', foto: '9MEConcheiro.jpg')
Investigador.create(email: 'molotla.cf@unam.mx', password: 'Aeid57', programa_id: '7', nombres: 'Felipe', apPat: 'Contreras', apMat: 'Molotla', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Por Artículo 51', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel B', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación La Producción de Bienes y Servicios Básicos', historiaAcademica: 'Doctor en Estudios de Población, El Colegio de México
Maestro en Población, Facultad Latinoamericana de Ciencias Sociales, Sede Académica México
Licenciado en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0263', extension:'', humanindex: '', foto: '10FContreras.jpg')
Investigador.create(email: 'consuar@unam.mx', password: 'Aiiid31', programa_id: '7', nombres: 'Enrique', apPat: 'Contreras', apMat: 'Suárez', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación La Producción de Bienes y Servicios Básicos', historiaAcademica: 'Doctor en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestro en Ciencias Sociales, Facultad Latinoamericana de Ciencias Sociales, Santiago de Chile
Licenciado en Ciencias Sociales, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0261', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=COSE410224', foto: '11EContreras.jpg')
#Investigador.create(email: 'correas@unam.mx', password: 'avioAn94', programa_id: '10', nombres: 'Oscar', apPat: 'Correas', apMat: 'Vázquez', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel III', adscripcion: 'Programa de investigación Drecho y Sociedad', historiaAcademica: 'Doctor en Derecho,Universidad de Saint Etienne, Francia
#Maestro en Ciencias Sociales, Facultad de Filosofía y Letras, Universidad Autónoma de Puebla
#Licenciado en Derecho, Universidad Católica de Córdoba', correo: '', telefono: '', extension:'', humanindex: '', foto: '12OCorreas.jpg')

#Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '13SLDaville.jpg')

#Aquí seguimos con el 12
Investigador.create(email: 'jose@delval1.com', password: 'anTa65', programa_id: '8', nombres: 'José Manuel', apPat: 'Del Val', apMat: 'Blanco', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: '', sociedades: '', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Licenciado en Etnología, Escuela Nacional de Antropología e Historia', correo: '', telefono: '', extension:'', humanindex: '', foto: '12JMDelVal.jpg')
Investigador.create(email: 'giandelgado@unam.mx', password: 'Prez66', programa_id: '6', nombres: 'Gian Carlo', apPat: 'Delgado', apMat: 'Ramos', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctor en Ciencias Ambientales, Universidad Autónoma de Barcelona, España
Maestro en Economía Ecológica y Gestión Ambiental, Universidad Autónoma de Barcelona, España
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0222', extension:'42777', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=DERG780608', foto: '13GCDelgado.jpg')
Investigador.create(email: 'estradaalbateresa52@gmail.com', password: '0fdg4', programa_id: '3', nombres: 'Alba Teresa', apPat: 'Estrada', apMat: 'Castañón', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Ciencia Social con Especialidad en Sociología, El Colegio de México
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0477', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=EACA511030', foto: '14ATEstrada.jpg')
Investigador.create(email: 'dfavelag@unam.mx', password: 'Caro71', programa_id: '8', nombres: 'Diana Margarita', apPat: 'Favela', apMat: 'Gavia', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencia Política, Universidad de Tulane, USA
Maestra en Economía Política Internacional, Centro de Investigación y Docencia Económicas, A. C.
Maestra en Ciencia Política, Universidad de Tulane, USA
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '2014mf02@gmail.com', telefono: '5623-0421', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=FAGD590416', foto: '15DMFavela.jpg')
Investigador.create(email: 'vfloresolea@gmail.com', password: 'sAlvar96', programa_id: '5', nombres: 'Víctor', apPat: 'Flores', apMat: 'Olea', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: '', estimulos: '', sociedades: '', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Estudios de Doctorado en Ciencias Políticas, Escuela Práctica de Altos Estudios, París
Licenciado en Derecho, Facultad de Derecho, UNAM', correo: '', telefono: '5623-0264', extension:'', humanindex: '', foto: '16VFlores.jpg')
Investigador.create(email: 'olivgall@unam.mx', password: 'Idff11', programa_id: '8', nombres: 'Olivia Joanna', apPat: 'Gall', apMat: 'Sonabend', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II
Miembro de la Academia Mexicana de Ciencias', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencia Política, Institut d’ Ètudes Politiques de Grenoble, Francia
Maestra en Ciencia Política, Institut d’ Ètudes Politiques de Grenoble, Francia
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42775', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GASO561021', foto: '17OGall.jpg')
Investigador.create(email: 'joseg@unam.mx', password: 'iana44', programa_id: '5', nombres: 'José Guadalupe', apPat: 'Gandarilla', apMat: 'Salgado', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Doctor en Filosofía Política, Universidad Autónoma Metropolitana-Iztapalapa
Maestro en Estudios Latinoamericanos, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciado en Economía, Facultad de Economía, UNAM', correo: '', telefono: '5623-0222', extension:'42766', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GASG671212', foto: '18JGGandarilla.jpg')
Investigador.create(email: 'tzolkin4@unam.mx', password: 'iuD5tr', programa_id: '4', nombres: 'Jorge Alejandro', apPat: 'González', apMat: 'Sánchez', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel III', adscripcion: 'Programa de Investigación Cibercultura y Desarrollo de Comunidades de Conocimiento', historiaAcademica: 'Doctor en Ciencias Sociales, Universidad Iberoamericana
Maestro en Sociología, Universidad Iberoamericana
Licenciado en Comunicación, Universidad Iberoamericana', correo: 'jorge@labcomplex.net', telefono: '5623-0449', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GOSJ541129', foto: '19JAGonzalez.jpg')
Investigador.create(email: 'guillermo.guajardo@unam.mx', password: 'fD9th', programa_id: '2', nombres: 'Guillermo Agustín', apPat: 'Guajardo', apMat: 'Soto', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Maestro en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Licenciado en Historia, Facultad de Filosofía y Humanidades, Universidad de Chile', correo: '', telefono: '5623-0431', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=GUSG620619', foto: '20GAGuajardo.jpg')
Investigador.create(email: 'FabrizzioMc@gmail.com', password: '34Mus', programa_id: '1', nombres: 'Siobhan Fenella', apPat: 'Guerrero', apMat: 'Mc Manus', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Estímulo Equivalente a PRIDE C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctor en Filosofía de la Ciencia por la UNAM, FFyL
Maestro en Filosofía de la Ciencia por la UNAM, FFyL
Biólogo por la UNAM, Facultad de Ciencias', correo: 'siobhanfgm@gmail.com', telefono: '5623-0222', extension:'42821', humanindex: '', foto: '21SFGuerrero.jpg')
Investigador.create(email: 'aleidahc@unam.mx', password: 'fg86', programa_id: '10', nombres: 'Aleida', apPat: 'Hernández', apMat: 'Cervantes', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Estímulo Equivalente a PRIDE C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Derecho y Sociedad', historiaAcademica: 'Doctora en Derecho, Facultad de Derecho, UNAM
Maestra en Derecho, Facultad de Derecho, UNAM
Licenciada Facultad de Derecho y Ciencias Sociales, UAS', correo: 'aleycristal@hotmail.com', telefono: '56-23-02-22', extension:'42823', humanindex: '', foto: '22AHernandez.jpg')
Investigador.create(email: 'levjardon@ciencias.unam.mx', password: '75fgfg', programa_id: '2', nombres: 'Lev Orlando', apPat: 'Jardón', apMat: 'Barbolla', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Estímulo Equivalente a PRIDE C', sociedades: 'Candidato al Sistema Nacional de Investigadores', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctorado en Ciencias Biomédicas, UNAM
Licenciado en Biología, UNAM', correo: 'levjardon@yahoo.com.mx', telefono: '56230222', extension:'42771', humanindex: '', foto: '23LOJardon.jpg')

#Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '26MEEJarquin.jpg')

Investigador.create(email: 'jjuarez@unam.mx', password: 'wedh67', programa_id: '8', nombres: ' Julio Vicente', apPat: 'Juárez', apMat: 'Gámiz', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Maestro y Doctor en Comunicación Política, Universidad de Sheffield, United Kingdom
Licenciado en Psicología, Facultad de Psicología, UNAM', correo: '', telefono: '5623-0222', extension:'42776', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=JUGJ730817', foto: '24JVJuarez.jpg')
Investigador.create(email: 'koppen@unam.mx', password: 'vbnF5', programa_id: '11', nombres: 'Elke', apPat: 'Koppen', apMat: 'Prubmann', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Estudios Visuales', historiaAcademica: 'Doctora en Bibliotecología y Estudios de la Información, Facultad de Filosofía y Letras, UNAM
Maestra en Bibliotecología, Facultad de Filosofía y Letras, UNAM
Licenciada en Sociología, Universidad de Bielefeld, Alemania', correo: 'elke.koppen@gmail.com', telefono: '5623-0433', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=KOPE531130', foto: '25EKoppen.jpg')
Investigador.create(email: 'alejandraleal@gmail.com ', password: 'jmn09', programa_id: '6', nombres: 'Alejandra María', apPat: 'Leal', apMat: 'Leal', nombramiento: 'Investigadora', categoria: 'Asociada', nivel: 'C', definitividad: 'Interina', estimulos: 'Estímulos Equivalente a PRIDE B y PEI', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Antropología Sociocultural, Universidad de Columbia, Nueva York
Maestra en Antropología Sociocultural, New School for Social Research, Nueva York
Licenciada en Historia, Universidad Nacional Autónoma de México', correo: '', telefono: '', extension:'', humanindex: '', foto: '26AMLeal.jpg')
Investigador.create(email: 'clegorreta@unam.mx', password: 'jhs34', programa_id: '8', nombres: 'María del Carmen', apPat: 'Legorreta', apMat: 'Díaz', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en "Ètudes sur l’ Amérique Latine", Université Toulouse Le-Mirail, Francia
Maestra en Ciencias del Desarrollo Rural Regional, Universidad Autó­noma de Chapingo
Licenciada en Sociología, Facultad de Ciencias Políticas Sociales, UNAM', correo: '', telefono: '5623-0412', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=LEDC601030', foto: '27MdCLegorreta.jpg')
Investigador.create(email: 'loezar@unam.mx', password: 'lkGP9', programa_id: '6', nombres: 'Laura', apPat: 'Loeza', apMat: 'Reyes', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Ciencia Política, Universidad de París I, Panthéon-Sorbonne
Maestra en Sociología Política, Instituto de Investigaciones Dr. José María Luis Mora
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42765', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=LORL611021', foto: '28LLoeza.jpg')
Investigador.create(email: 'paulapezca@unam.mx', password: 'QfW09', programa_id: '8', nombres: 'Paula', apPat: 'López', apMat: 'Caballero', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Antropología Social y Etnología, École des Hautes Études en Sciences Sociales, París, Francia
Maestra en Antropología Social y Etnología, École des Hautes Études en Sciences Sociales, París, Francia
Licenciada en Historia, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0222', extension:'42807', humanindex: '', foto: '29PLopez.jpg')
Investigador.create(email: 'jahellg1973@yahoo.com.mx', password: 'rxri7', programa_id: '9', nombres: 'Jahel', apPat: 'López', apMat: 'Guerrero', nombramiento: 'Investigadora', categoria: 'Asociada', nivel: 'C', definitividad: 'Interina', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Feminista', historiaAcademica: 'Doctora en Antropología, Facultad de Filosofía y Letras/Instituto de investigaciones Antropológicas, UNAM
Maestra en Antropología Social, Centro de Investigaciones y Estudios Superiores en Antropología Social, México
Licenciada en Etnología, Escuela Nacional de Antropología e Historia', correo: '', telefono: '5623-0264', extension:'', humanindex: '', foto: '30JLopez.jpg')
Investigador.create(email: 'rosalial@unam.mx', password: 'Maell', programa_id: '7', nombres: 'Rosalía', apPat: 'López', apMat: 'Paniagua', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación La producción de Bienes y Servicios Básicos', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Sociología Política, Instituto Dr. José María Luis Mora
Licenciada en Sociología, Escuela Nacional de Estudios Profesionales Aragón, UNAM', correo: '', telefono: '', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=LOPR570411', foto: '31RLopez.jpg')
Investigador.create(email: 'mmaass@unam.mx', password: 'naeYos', programa_id: '4', nombres: 'Elisa Margarita', apPat: 'Maass', apMat: 'Moreno', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Cibercultura y Desarrollo de Comunidades de Conocimiento', historiaAcademica: 'Doctora en Ciencias Sociales, Universidad Iberoamericana
Maestra en Comunicación, Universidad Iberoamericana
Licenciada en Conservación y Restauración de Bienes Muebles, Instituto Nacional de Antropología e Historia
Curso la Licenciatura en Historia, Facultad de Filosofía y Letras, UNAM', correo: 'margarita_maass@yahoo.com.mx', telefono: '5623-0222', extension:'42805', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=MAME580722', foto: '32EMMaass.jpg')
Investigador.create(email: 'mansy@unam.mx', password: 'T%Eev', programa_id: '2', nombres: 'Ricardo Lino', apPat: 'Mansilla', apMat: 'Corona', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Matemáticas, Universidad de La Habana, Cuba
Master of Arts in Economics, University of Carleton, Canadá
Licenciado en Matemáticas, Facultad de Ciencias, Universidad de La Habana, Cuba', correo: '', telefono: '5623-0435', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/pagina/pagina_inicio.php?rfc=MACR550923', foto: '33RLMansilla.jpg')
Investigador.create(email: 'gisela.mateos@unam.mx', password: 'si56cSe', programa_id: '1', nombres: 'Gisela Tamhara', apPat: 'Mateos', apMat: 'González', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctora en Historia de la Ciencia, Universidad Autónoma de Barcelona, España
Maestra en Historia de la Ciencia, Universidad Autónoma de Barcelona, España
Física, Facultad de Ciencias, UNAM', correo: '', telefono: '5623-0265', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=MAGG660718', foto: '34GTMateos.jpg')
Investigador.create(email: 'jfmoralesb@gmail.com', password: 'ossm09', programa_id: '6', nombres: 'José Federico', apPat: 'Morales', apMat: 'Barragán', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctor en Ecología y Desarrollo Sostenible, El Colegio de la Frontera Sur
Maestro en Ciencias Económicas, UNAM
Licenciado en Economía, UNACH', correo: '', telefono: '5623 0022', extension:'42792', humanindex: '', foto: '35JFMorales.jpg')
Investigador.create(email: 'rsarabia@unam.mx', password: 'ares', programa_id: '1', nombres: 'Rosa Angélica', apPat: 'Morales', apMat: 'Sarabia', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores I', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctora en Historia, Facultad de Filosofía y Letras, UNAM
Maestra en Historia, Universidad Iberoamericana
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0450', extension:'', humanindex: '', foto: '36RAMorales.jpg')

#Investigador.create(email: '', password: '123456', programa_id: '', nombres: '', apPat: '', apMat: '', nombramiento: '', categoria: '', nivel: '', definitividad: '', estimulos: '', sociedades: '', adscripcion: '', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '40JMunoz.jpg')

Investigador.create(email: 'aqny@unam.mx', password: 'siM7', programa_id: '2', nombres: 'Aquiles', apPat: 'Negrete', apMat: 'Yankelevich', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Comunicación Científica, Universidad de Bath, Reino Unido
Maestro en Manejo de Recursos Naturales, Universidad de Edimburgo, Reino Unido
Licenciado en Biología, Facultad de Ciencias, UNAM
Especialidad en Ciencias de la Computación, Fundación Arturo Rosenblueth', correo: '', telefono: '5623-0444', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=NEYA660816', foto: '37ANegrete.jpg')
Investigador.create(email: 'snicco@colmex.mx', password: 'el6M', programa_id: '1', nombres: 'Sergio', apPat: 'Niccolai', apMat: 'Salvadori', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: '', sociedades: '', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Doctorado en Historia de las Américas (DR, PhD), Universidad de los Estudios de Génova, Italia
Maestro en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Laurea de Doctor en Filosofía (DL, MD - antigua titulación), Universidad de los Estudios de Pisa, Italia', correo: '', telefono: '5623-0271', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=NISS600517', foto: '38SNiccolai.jpg')
Investigador.create(email: 'teresaos@unam.mx', password: 'alin#', programa_id: '9', nombres: 'Teresa', apPat: 'Ordorika', apMat: 'Sacristán', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores I', adscripcion: 'Programa Investigación Feminista', historiaAcademica: 'Doctora en Sociología, University of London
Maestra en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0429', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=NISS600517', foto: '39TOrdorika.jpg')
Investigador.create(email: 'oquesada@unam.mx', password: 'sios8', programa_id: '11', nombres: 'Octavio', apPat: 'Quesada', apMat: 'García', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel A', sociedades: 'Sistema Nacional de Investigadores Nivel I', adscripcion: 'Programa de Investigación Estudios Visuales', historiaAcademica: 'Doctor en Ciencias Biomédicas (Neuroquímica), Facultad de Medicina / Instituto de Fisiología Celular, UNAM
Maestro en Investigación Biomédica Básica, UACPyP del CCH / Instituto de Fisiología Celular, UNAM
Biólogo, Facultad de Ciencias, UNAM', correo: '', telefono: '5623-0270', extension:'', humanindex: '', foto: '40OQuesada.jpg')
Investigador.create(email: 'ramoslm@unam.mx', password: '12nar', programa_id: '2', nombres: 'María de la Paz', apPat: 'Ramos', apMat: 'Lara', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctora en Historia, Facultad de Filosofía y Letras, UNAM
Maestra en Ciencias Físicas, Facultad de Ciencias, UNAM
Física, Facultad de Ciencias, UNAM', correo: '', telefono: '5623-0430', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=RALP620124', foto: '41MdlPRamos.jpg')
Investigador.create(email: 'menchero@unam.mx', password: 'de5vi', programa_id: '11', nombres: 'Mauricio', apPat: 'Sánchez', apMat: 'Menchero', nombramiento: 'Investigador', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Estudios Visuales', historiaAcademica: 'Maestro y Doctor en Historia y Comunicación en el Mundo Contemporáneo, Facultad de Ciencias de la Información, Universidad Complutense de Madrid, España
Licenciado en Ciencias de la Comunicación Social, Universidad Autónoma Metropolitana-Xochimilco', correo: '', telefono: '5623-0222', extension:'42778', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=SAMM620704', foto: '42MSanchez.jpg')
Investigador.create(email: 'saxe@unam.mx', password: 'S4x3F', programa_id: '5', nombres: 'John', apPat: 'Saxe', apMat: 'Fernández', nombramiento: 'Profesor', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel ', sociedades: 'Sistema Nacional de Investigadores nivel III', adscripcion: 'Programa de Investigación El Mundo en el Siglo XXI', historiaAcademica: 'Doctor en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Maestro en Estudios Latinoamericanos, Universidad de Washington, St. Louis Missouri, USA
Licenciado en Ciencia Política, Universidad de Brandeis, Waltham Massachussets', correo: '', telefono: '5623-0198', extension:'', humanindex: '', foto: '43JSaxe.jpg')
Investigador.create(email: 'tena@unam.mx', password: 'OP8d', programa_id: '9', nombres: 'Olivia', apPat: 'Tena', apMat: 'Guerrero', nombramiento: 'Profesora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Feminista', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Psicología: Metodología de la Investigación Teórica y Conduc­tual, Facultad de Estudios Superiores Iztacala, UNAM
Licenciada en Psicología, Facultad de Estudios Superiores Iztacala, UNAM', correo: '', telefono: '5623-0222', extension:'42761', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=TEGO590105', foto: '44OTena.jpg')
Investigador.create(email: 'valencia@unam.mx', password: '123456', programa_id: '3', nombres: 'Guadalupe', apPat: 'Valencia', apMat: 'García', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM
Maestra en Sociología Política, Instituto de Investigaciones Dr. José María Luis Mora
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0440', extension:'', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=VAGG571103', foto: '45GValencia.jpg')
Investigador.create(email: 'aimeevegamx@yahoo.com.mx', password: 'ar9rio', programa_id: '9', nombres: 'Medley Aimeé', apPat: 'Vega', apMat: 'Montiel', nombramiento: 'Investigadora', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: 'Sistema Nacional de Investigadores nivel II', adscripcion: 'Programa de Investigación Feminista', historiaAcademica: 'Doctora en Periodismo y Ciencias de la Comunicación, Universidad Autónoma de Barcelona
Maestra en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM
Máster en Periodismo y Ciencias de la Comunicación, Universidad Autónoma de Barcelona
Licenciada en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-2300', extension:'42774', humanindex: 'http://www.humanindex.unam.mx/humanindex/consultas/detalle_investigadores.php?rfc=VEMM740303', foto: '46MAVega.jpg')
Investigador.create(email: 'ayari.pasquier@unam.mx', password: '123456', programa_id: '6', nombres: 'Ayari', apPat: 'Pasquier', apMat: 'Merino', nombramiento: 'Investigadora', categoria: 'Asociada', nivel: 'C', definitividad: 'Por Artículo 51', estimulos: '', sociedades: 'Candidata al Sistema Nacional de Investigadores', adscripcion: 'Programa de Investigación Ciudades, Gestión, Territorio y Ambiente', historiaAcademica: 'Doctora en Ciencias Sociales (Sociología), Centro de Estudios Sociológicos, Colegio de México
Maestra en Antropología, Alma Mater Studiorum, Università Di Bologna
Licenciada en Comunicación Social, Universidad Autónoma Metropolitana-Xochimilco ', correo: 'ayaripasquier@gmail.com', telefono: '', extension:'', humanindex: '', foto: '')

Tecnico.create(email: 'alegre@unam.mx', password: 'offy26', nombres: 'María de los Ángeles Consuelo', apPat: 'Alegre', apMat: 'Schettino', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Maestría en Diseño y Comunicación Visual, Facultad de Artes y  Diseño, UNAM
Licenciada en Diseño Gráfico, Escuela Nacional de Artes Plásticas, UNAM', correo: '', telefono: '5623-0222', extension:'42063', humanindex: '', foto: '1MdlACAlegre.jpg')
Tecnico.create(email: 'carrillopatricia4@gmail.com', password: 'ieF27', nombres: 'Lucía Patricia', apPat: 'Carrillo', apMat: 'Velázquez', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: 'Sistema Nacional de Investigadores nivel I', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencias de la Administración, Facultad de Contaduría y Administración, UNAM
Investigación Posdoctoral, Investigación Científica Básica SEP-CONACyT
Maestra en Administración de Organizaciones, Facultad de Contaduría y Administración, UNAM
Ingeniera en Computación, Facultad de Ingeniería, UNAM', correo: 'carrillopaty@hotmail.com', telefono: '5623-0222', extension:'42808', humanindex: 'humanindex.unam.mx/humanindex/pagina/pagina_inicio_tecnicos.php?rfc=CAVL620501', foto: '2LPCarrillo.jpg')
Tecnico.create(email: 'casale@unam.mx', password: 'ern$ad67', nombres: 'Concepción Alida', apPat: 'Casale', apMat: 'Núñez ', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Maestra en Psicoterapia Psicoanalítica, Centro ELEIA
Matemática, Facultad de Ciencias, UNAM', correo: '', telefono: '5623-0222', extension:'42061', humanindex: '', foto: '3CACasale.jpg')
Tecnico.create(email: 'clarae@unam.mx', password: 'Aerto86', nombres: 'Clara Elizabeth', apPat: 'Castillo', apMat: 'Álvarez', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Estudiante de la Maestría en Historia del Arte, Facultad de Filosofía y Letras, UNAM
Licenciada en Periodismo, Escuela de Periodismo Carlos Septién García', correo: '', telefono: '5623-0222', extension:'42060', humanindex: '', foto: '4CECastillo.jpg')
Tecnico.create(email: 'mgcg@unam.mx', password: 'rEfdgs63', nombres: 'María Gladys de Guadalupe', apPat: 'Castillo', apMat: 'Guerrero', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Por artículo 51', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Difusión', historiaAcademica: 'Contadora Pública, Universidad Autónoma del Sudeste, Campeche', correo: '', telefono: '5623-0222', extension:'42804', humanindex: '', foto: '5MGCastillo.jpg')
Tecnico.create(email: 'amanali.cv@gmail.com', password: 'nalei74', nombres: 'Amanali María', apPat: 'Cornejo', apMat: 'Vázquez', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'B', definitividad: 'Interina', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel B', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '6AMCornejo.jpg')
Tecnico.create(email: 'clausrio@unam.mx', password: 'noD46', nombres: 'Claudia Gabriela', apPat: 'del Río', apMat: 'Rodríguez', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Doctora en Ciencias de Desarrollo Rural Regional, Universidad Autónoma Chapingo
Maestra en Comunicación de la Facultad de Ciencias Políticas y Sociales-UNAM
Licenciada en Sociología, UAM', correo: '', telefono: '5623-0269', extension:'', humanindex: '', foto: '7CGDelRio.jpg')
Tecnico.create(email: 'gustavoe@unam.mx', password: 'dhg06', nombres: 'Gustavo', apPat: 'Enríquez', apMat: 'Téllez', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Información y Documentación', historiaAcademica: 'Licenciado en Biblioteconomía, Escuela Nacional de Biblioteconomía y Archivonomía', correo: '', telefono: '5623-0445', extension:'', humanindex: '', foto: '8GEnriquez.jpg')
Tecnico.create(email: 'villela@unam.mx', password: 'elJ5es64', nombres: 'Carlos Arturo', apPat: 'Flores', apMat: 'Villela', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Estudios Visuales', historiaAcademica: 'Maestro en Historia del Arte, Facultad de Filosofía y letras, UNAM
Licenciado en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0422', extension:'', humanindex: '', foto: '9CAFlores.jpg')
Tecnico.create(email: 'mhgb@unam.mx', password: 'An5fgC51', nombres: 'María Haydeé', apPat: 'García', apMat: 'Bravo', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Historia de la Ciencia', historiaAcademica: 'Maestra en Antropología Social, Escuela Nacional de Antropología e Historia
Maestra en Historia y Patrimonio, Master Erasmus Mundus TPTI, Universidad Paris 1 Pantheon-Sorbonne
Licenciada en Ciencias de la Comunicación, Universidad de San Luis Potosí', correo: 'mahaydee@yahoo.com', telefono: '5623-0262', extension:'', humanindex: '', foto: '10MHGarcia.jpg')
Tecnico.create(email: 'lgu@unam.mx', password: 'hf34dh', nombres: 'Leonor', apPat: 'García', apMat: 'Urbano', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Apoyo a la Docencia, Educación Continua y Diplomados', historiaAcademica: 'Maestra en Bibliotecología y Estudios de la Información, Facultad de Filosofía y Letras, UNAM
Licenciada en Bibliotecología, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0417', extension:'', humanindex: '', foto: '11LGarcia.jpg')
Tecnico.create(email: 'jfjimc@unam.mx', password: 'siu98', nombres: 'Josefina', apPat: 'Jiménez', apMat: 'Cortés', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Pasante de la Licenciatura en Letras Hispanoamericanas, Universidad Autónoma Metropolitana Iztapalapa', correo: '', telefono: '5623-0222', extension:'42063', humanindex: '', foto: '12JJimenez.jpg')
Tecnico.create(email: 'labrador@unam.mx', password: 'fghP9', nombres: 'Alejandro', apPat: 'Labrador', apMat: 'Sánchez', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'C', definitividad: 'Interino', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Estudios de Maestría en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Licenciado en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0434', extension:'', humanindex: '', foto: '13ALabrador.jpg')
Tecnico.create(email: 'mrlt@unam.mx', password: 'hJH98', nombres: 'Rogelio', apPat: 'López', apMat: 'Torres', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Estudios de Doctorado en Fisiología y Biofísica, Centro de Investigación y Estudios Avanzados, IPN
Maestría en Ciencias en Fisiología y Biofísica, Centro de Investigación y Estudios Avanzados, IPN
Egresado de la Facultad de Medicina, UNAM', correo: '', telefono: '5623-0222', extension:'42773', humanindex: '', foto: '14RLopez.jpg')
Tecnico.create(email: 'brissa@unam.mx', password: 'iesp3s', nombres: 'Brisa Jessica', apPat: 'Luna', apMat: 'Sabás', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Cómputo', historiaAcademica: '', correo: '', telefono: '5623-0207', extension:'', humanindex: '', foto: '15BJLuna.jpg')
Tecnico.create(email: 'victormm@unam.mx', password: 's6mvi', nombres: 'Víctor Manuel', apPat: 'Méndez', apMat: 'Villanueva', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'A', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: '', adscripcion: 'Departamento de Producción Audiovisual y Multimedia', historiaAcademica: 'Licenciado en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0206', extension:'', humanindex: '', foto: '16VMMendez.jpg')
Tecnico.create(email: 'tzunum13@gmail.com', password: 'es3se', nombres: 'Dora Evangelina', apPat: 'Mendizábal', apMat: 'García', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Interina', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Maestra en Ciencias Sociales, Centro de Investigaciones y Estudios Superiores en Antropología Social, CIESAS Centro
Licenciada en Ciencias Jurídicas y Sociales, Universidad de San Carlos de Guatemala', correo: '', telefono: '', extension:'', humanindex: '', foto: '17DEMendizabal.jpg')
Tecnico.create(email: 'romanero@unam.mx', password: 'ev8Se', nombres: 'Rosa María', apPat: 'Mendoza', apMat: 'Rosas', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Candidata a la Maestría en Geografía con Orientación en Territorio y Sociedad, Facultad de Filosofía y Letras, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42806', humanindex: '', foto: '18RMMendoza.jpg')
Tecnico.create(email: 'hmendoza@unam.mx', password: 'ar8es', nombres: 'Hermelinda', apPat: 'Villavicencio', apMat: 'Mendoza', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa Investigación Feminista', historiaAcademica: 'Créditos de la Maestría en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Licenciada en Sociología, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0446', extension:'', humanindex: '', foto: '19HMendoza.jpg')
Tecnico.create(email: 'moncadal@unam.mx', password: 'i5ase', nombres: 'Alma Laura', apPat: 'Moncada', apMat: 'Marín', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Maestra en Bibliotecología y Estudios de la Información, Facultad de Filosofía y Letras, UNAM
Licenciada en Comunicación y Periodismo Colectivo, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0432', extension:'', humanindex: '', foto: '20ALMoncada.jpg')
Tecnico.create(email: 'zafra@unam.mx', password: 'ioad', nombres: 'Liliana Josefina', apPat: 'Muñiz', apMat: 'Zafra', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Cómputo', historiaAcademica: 'Maestra en Administración, Facultad de Contaduría y Administración, UNAM
Ingeniera en Computación, Facultad de Ingeniería, UNAM', correo: '', telefono: '5623-0222', extension:'42820', humanindex: '', foto: '21LJMuniz.jpg')
Tecnico.create(email: 'olivera@unam.mx', password: 'spin83', nombres: 'María Elena', apPat: 'Olivera', apMat: 'Córdova', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'C', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: '', adscripcion: 'Programa de Investigación Ciencias Sociales y Literatura', historiaAcademica: 'Doctora en Humanidades con línea en Teoría Literaria por la Universidad Autónoma Metropolitana Iztapalapa
Maestra en Literatura Mexicana, Facultad de Filosofía y Letras, UNAM
Licenciada en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0267', extension:'', humanindex: '', foto: '22MEOlivera.jpg')
Tecnico.create(email: 'lolivos@unam.mx', password: 'x23ta', nombres: 'Leonardo Felipe', apPat: 'Olivos', apMat: 'Santoyo', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Feminista', historiaAcademica: 'Programa de posgrado en estudios latinoamericanos
Maestro en Estudios Políticos y Sociales, Facultad de Ciencias Políticas y Sociales, UNAM
Licenciado en Ciencia Política y Administración Pública, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0420', extension:'', humanindex: '', foto: '23LFOlivos.jpg')
Tecnico.create(email: 'nicolasa@unam.mx', password: 'itin3', nombres: 'Nicolasa', apPat: 'Ramírez', apMat: 'Vicente', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Información y Documentación', historiaAcademica: 'Licenciada en Bibliotecología, Facultad de Filosofía y Letras, UNAM', correo: '', telefono: '5623-0031', extension:'', humanindex: '', foto: '24NRamirez.jpg')
Tecnico.create(email: 'carolashz@gmail.com', password: 'spx6', nombres: 'Carolina', apPat: 'Sánchez', apMat: 'García', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'A', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Poder, Subjetividad y Cultura', historiaAcademica: 'Licenciada en Antropología Social, Escuela Nacional de Antropología e Historia', correo: '', telefono: '', extension:'', humanindex: '', foto: '25CSanchez.jpg')
Tecnico.create(email: 'isauribe@unam.mx', password: 'in4sp', nombres: 'Isauro', apPat: 'Uribe', apMat: 'Pineda', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel D', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: 'Licenciado en Diseño de la Comunicación Gráfica, Universidad Autónoma Metropolitana-Xochimilco', correo: '', telefono: '5623-0022', extension:'42061', humanindex: '', foto: '26IUribe.jpg')
Tecnico.create(email: 'paulovazquez@yahoo.com.mx', password: '56nta', nombres: 'Paulo César', apPat: 'Vázquez', apMat: 'Pacheco', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'B', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel B', sociedades: '', adscripcion: 'Departamento de Producción Audiovisual y Multimedia', historiaAcademica: 'Licenciado en Ciencias de la Comunicación, Facultad de Ciencias Políticas y Sociales, UNAM', correo: '', telefono: '5623-0222', extension:'42787', humanindex: '', foto: '27PCVazquez.jpg')
Tecnico.create(email: 'visar@unam.mx', password: '2adis', nombres: 'Juan Carlos', apPat: 'Villa', apMat: 'Soto', nombramiento: 'Técnico', categoria: 'Titular', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Programa de Investigación Ciencia y Tecnología', historiaAcademica: 'Doctor en Estudios Latinoamericanos, Facultad de Filosofía y Letras, UNAM
Maestro en Economía y Gestión del Cambio Tecnológico, UAM-Xochi­milco
Licenciado en Psicología, Escuela Nacional de Estudios Profesionales-Iztacala, UNAM', correo: '', telefono: '5623-0222', extension:'42770', humanindex: '', foto: '28JCVilla.jpg')
Tecnico.create(email: 'anaelisa30@gmail.com', password: 'it68', nombres: 'Ana Elisa', apPat: 'Villarreal', apMat: 'Barrón', nombramiento: 'Técnica', categoria: 'Asociada', nivel: 'C', definitividad: 'Por Artículo 51', estimulos: 'Estímulo Equivalente PRIDE B', sociedades: '', adscripcion: 'Apoyo a la Docencia, Educación Continua y Diplomados ', historiaAcademica: 'Pasante de Licenciatura', correo: '', telefono: '5623-0222', extension:'42784', humanindex: '', foto: '29AEVillarreal.jpg')

Tecnico.create(email: '', password: 'C0r73', nombres: 'Mercedes', apPat: 'Cortez', apMat: 'Arriaga', nombramiento: 'Técnica', categoria: 'Titular', nivel: 'B', definitividad: 'Definitiva', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Departamento de Publicaciones', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')
Tecnico.create(email: 'garod@unam.mx', password: 'Gaga66', nombres: 'Humberto', apPat: 'García', apMat: 'Rodríguez', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'C', definitividad: 'Definitivo', estimulos: 'Programa de Primas al Desempeño del Personal Académico de Tiempo Completo nivel C', sociedades: '', adscripcion: 'Planeación y Seguimiento Académico', historiaAcademica: '', correo: '', telefono: '', extension:'', humanindex: '', foto: '')
Tecnico.create(email: 'jorge.pm@ceiich.unam.mx', password: 'ceiich2018', nombres: 'Jorge', apPat: 'Pantaleón', apMat: 'Martínez', nombramiento: 'Técnico', categoria: 'Asociado', nivel: 'C', definitividad: 'Por Artículo 51', estimulos: 'Estímulo Equivalente PRIDE B', sociedades: '', adscripcion: 'Departamento de Cómputo', historiaAcademica: 'Maestro en Ingeniería en Computación, Posgrado en Ciencia e Ingeniería de la Computación, UNAM
Ingeniero Computación, Facultad de Ingeniería, UNAM', correo: '', telefono: '5623-0204', extension:'', humanindex: '', foto: '')
